name: aws-glue-connection-plugin
description: AWS Glue connection Plugin
display-name: aws-glue-connection-plugin
picture: plugin.png
category: backend # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#category
compatibility:
  - Terraform
about: docs/about.md
usage: docs/usage.md
use-case: docs/use-case.md
implementation: docs/implementation.md
technologies: # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#technologies
  - "Api"
types:
  - env
inputs:
  - label: Qual será o nome da connection?
    type: text
    name: connection_name
    
  - label: Qual será o tipo da connection?
    type: text
    items:
      - S3
      - JDBC
    name: connection_type

  - label: Qual será a descrição da connection?
    type: text
    name: connection_description